# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arolland/LooCpp/BlindTestTagManager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arolland/LooCpp/BlindTestTagManager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arolland/LooCpp/BlindTestTagManager/CMakeFiles /home/arolland/LooCpp/BlindTestTagManager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arolland/LooCpp/BlindTestTagManager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bttManager

# Build rule for target.
bttManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bttManager
.PHONY : bttManager

# fast build rule for target.
bttManager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/build
.PHONY : bttManager/fast

#=============================================================================
# Target rules for targets named test_tagManager

# Build rule for target.
test_tagManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tagManager
.PHONY : test_tagManager

# fast build rule for target.
test_tagManager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/build
.PHONY : test_tagManager/fast

#=============================================================================
# Target rules for targets named test_bttManager

# Build rule for target.
test_bttManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bttManager
.PHONY : test_bttManager

# fast build rule for target.
test_bttManager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/build
.PHONY : test_bttManager/fast

#=============================================================================
# Target rules for targets named checkTags

# Build rule for target.
checkTags: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 checkTags
.PHONY : checkTags

# fast build rule for target.
checkTags/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/build
.PHONY : checkTags/fast

#=============================================================================
# Target rules for targets named prepareTags

# Build rule for target.
prepareTags: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prepareTags
.PHONY : prepareTags

# fast build rule for target.
prepareTags/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/build
.PHONY : prepareTags/fast

#=============================================================================
# Target rules for targets named dumpTags

# Build rule for target.
dumpTags: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dumpTags
.PHONY : dumpTags

# fast build rule for target.
dumpTags/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/build
.PHONY : dumpTags/fast

src/bttManager_main.o: src/bttManager_main.cpp.o
.PHONY : src/bttManager_main.o

# target to build an object file
src/bttManager_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttManager_main.cpp.o
.PHONY : src/bttManager_main.cpp.o

src/bttManager_main.i: src/bttManager_main.cpp.i
.PHONY : src/bttManager_main.i

# target to preprocess a source file
src/bttManager_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttManager_main.cpp.i
.PHONY : src/bttManager_main.cpp.i

src/bttManager_main.s: src/bttManager_main.cpp.s
.PHONY : src/bttManager_main.s

# target to generate assembly for a file
src/bttManager_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttManager_main.cpp.s
.PHONY : src/bttManager_main.cpp.s

src/bttParser.o: src/bttParser.cpp.o
.PHONY : src/bttParser.o

# target to build an object file
src/bttParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/bttParser.cpp.o
.PHONY : src/bttParser.cpp.o

src/bttParser.i: src/bttParser.cpp.i
.PHONY : src/bttParser.i

# target to preprocess a source file
src/bttParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/bttParser.cpp.i
.PHONY : src/bttParser.cpp.i

src/bttParser.s: src/bttParser.cpp.s
.PHONY : src/bttParser.s

# target to generate assembly for a file
src/bttParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/bttParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/bttParser.cpp.s
.PHONY : src/bttParser.cpp.s

src/checkTags.o: src/checkTags.cpp.o
.PHONY : src/checkTags.o

# target to build an object file
src/checkTags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/checkTags.cpp.o
.PHONY : src/checkTags.cpp.o

src/checkTags.i: src/checkTags.cpp.i
.PHONY : src/checkTags.i

# target to preprocess a source file
src/checkTags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/checkTags.cpp.i
.PHONY : src/checkTags.cpp.i

src/checkTags.s: src/checkTags.cpp.s
.PHONY : src/checkTags.s

# target to generate assembly for a file
src/checkTags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/checkTags.cpp.s
.PHONY : src/checkTags.cpp.s

src/dumpTags.o: src/dumpTags.cpp.o
.PHONY : src/dumpTags.o

# target to build an object file
src/dumpTags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/dumpTags.cpp.o
.PHONY : src/dumpTags.cpp.o

src/dumpTags.i: src/dumpTags.cpp.i
.PHONY : src/dumpTags.i

# target to preprocess a source file
src/dumpTags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/dumpTags.cpp.i
.PHONY : src/dumpTags.cpp.i

src/dumpTags.s: src/dumpTags.cpp.s
.PHONY : src/dumpTags.s

# target to generate assembly for a file
src/dumpTags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/dumpTags.cpp.s
.PHONY : src/dumpTags.cpp.s

src/lib_bttManager.o: src/lib_bttManager.cpp.o
.PHONY : src/lib_bttManager.o

# target to build an object file
src/lib_bttManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/lib_bttManager.cpp.o
.PHONY : src/lib_bttManager.cpp.o

src/lib_bttManager.i: src/lib_bttManager.cpp.i
.PHONY : src/lib_bttManager.i

# target to preprocess a source file
src/lib_bttManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/lib_bttManager.cpp.i
.PHONY : src/lib_bttManager.cpp.i

src/lib_bttManager.s: src/lib_bttManager.cpp.s
.PHONY : src/lib_bttManager.s

# target to generate assembly for a file
src/lib_bttManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/lib_bttManager.cpp.s
.PHONY : src/lib_bttManager.cpp.s

src/prepareTags.o: src/prepareTags.cpp.o
.PHONY : src/prepareTags.o

# target to build an object file
src/prepareTags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/prepareTags.cpp.o
.PHONY : src/prepareTags.cpp.o

src/prepareTags.i: src/prepareTags.cpp.i
.PHONY : src/prepareTags.i

# target to preprocess a source file
src/prepareTags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/prepareTags.cpp.i
.PHONY : src/prepareTags.cpp.i

src/prepareTags.s: src/prepareTags.cpp.s
.PHONY : src/prepareTags.s

# target to generate assembly for a file
src/prepareTags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/prepareTags.cpp.s
.PHONY : src/prepareTags.cpp.s

src/tagManager.o: src/tagManager.cpp.o
.PHONY : src/tagManager.o

# target to build an object file
src/tagManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/tagManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/tagManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/tagManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/tagManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/tagManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/tagManager.cpp.o
.PHONY : src/tagManager.cpp.o

src/tagManager.i: src/tagManager.cpp.i
.PHONY : src/tagManager.i

# target to preprocess a source file
src/tagManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/tagManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/tagManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/tagManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/tagManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/tagManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/tagManager.cpp.i
.PHONY : src/tagManager.cpp.i

src/tagManager.s: src/tagManager.cpp.s
.PHONY : src/tagManager.s

# target to generate assembly for a file
src/tagManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bttManager.dir/build.make CMakeFiles/bttManager.dir/src/tagManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/tagManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/tagManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/checkTags.dir/build.make CMakeFiles/checkTags.dir/src/tagManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prepareTags.dir/build.make CMakeFiles/prepareTags.dir/src/tagManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumpTags.dir/build.make CMakeFiles/dumpTags.dir/src/tagManager.cpp.s
.PHONY : src/tagManager.cpp.s

src/test_bttManager.o: src/test_bttManager.cpp.o
.PHONY : src/test_bttManager.o

# target to build an object file
src/test_bttManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/test_bttManager.cpp.o
.PHONY : src/test_bttManager.cpp.o

src/test_bttManager.i: src/test_bttManager.cpp.i
.PHONY : src/test_bttManager.i

# target to preprocess a source file
src/test_bttManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/test_bttManager.cpp.i
.PHONY : src/test_bttManager.cpp.i

src/test_bttManager.s: src/test_bttManager.cpp.s
.PHONY : src/test_bttManager.s

# target to generate assembly for a file
src/test_bttManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bttManager.dir/build.make CMakeFiles/test_bttManager.dir/src/test_bttManager.cpp.s
.PHONY : src/test_bttManager.cpp.s

src/test_tagManager.o: src/test_tagManager.cpp.o
.PHONY : src/test_tagManager.o

# target to build an object file
src/test_tagManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/test_tagManager.cpp.o
.PHONY : src/test_tagManager.cpp.o

src/test_tagManager.i: src/test_tagManager.cpp.i
.PHONY : src/test_tagManager.i

# target to preprocess a source file
src/test_tagManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/test_tagManager.cpp.i
.PHONY : src/test_tagManager.cpp.i

src/test_tagManager.s: src/test_tagManager.cpp.s
.PHONY : src/test_tagManager.s

# target to generate assembly for a file
src/test_tagManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tagManager.dir/build.make CMakeFiles/test_tagManager.dir/src/test_tagManager.cpp.s
.PHONY : src/test_tagManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bttManager"
	@echo "... checkTags"
	@echo "... dumpTags"
	@echo "... prepareTags"
	@echo "... test_bttManager"
	@echo "... test_tagManager"
	@echo "... src/bttManager_main.o"
	@echo "... src/bttManager_main.i"
	@echo "... src/bttManager_main.s"
	@echo "... src/bttParser.o"
	@echo "... src/bttParser.i"
	@echo "... src/bttParser.s"
	@echo "... src/checkTags.o"
	@echo "... src/checkTags.i"
	@echo "... src/checkTags.s"
	@echo "... src/dumpTags.o"
	@echo "... src/dumpTags.i"
	@echo "... src/dumpTags.s"
	@echo "... src/lib_bttManager.o"
	@echo "... src/lib_bttManager.i"
	@echo "... src/lib_bttManager.s"
	@echo "... src/prepareTags.o"
	@echo "... src/prepareTags.i"
	@echo "... src/prepareTags.s"
	@echo "... src/tagManager.o"
	@echo "... src/tagManager.i"
	@echo "... src/tagManager.s"
	@echo "... src/test_bttManager.o"
	@echo "... src/test_bttManager.i"
	@echo "... src/test_bttManager.s"
	@echo "... src/test_tagManager.o"
	@echo "... src/test_tagManager.i"
	@echo "... src/test_tagManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

